import type { Category, Product } from '@/lib/types';
import { Apple, Carrot, Milk, Soup, Sandwich, Fish, Cookie, Coffee, GlassWater, Sparkles, Hand, Grip } from 'lucide-react';

export const categories: Category[] = [
  { id: 'all', name_en: 'All', name_hi: 'सब', slug: 'all', icon: Grip },
  { 
    id: '1', 
    name_en: 'Vegetables & Fruits', 
    name_hi: 'सब्जियाँ और फल', 
    slug: 'vegetables-fruits', 
    icon: Carrot,
    subCategories: [
      "Fresh Vegetables",
      "Fresh Fruits",
      "Organic",
      "Cut & Chopped",
      "Leafy Greens",
      "Seasonal Fruits"
    ]
  },
  { 
    id: '3', 
    name_en: 'Dairy & Bakery', 
    name_hi: 'दूध और बेकरी', 
    slug: 'dairy-bakery', 
    icon: Milk,
    subCategories: [
      "Milk",
      "Bread",
      "Cheese",
      "Butter",
      "Paneer",
      "Curd & Yogurt",
      "Bakery Snacks",
      "Cakes & Pastries"
    ]
  },
  { 
    id: '4', 
    name_en: 'Staples & Grocery', 
    name_hi: 'किराना', 
    slug: 'groceries', 
    icon: Soup,
    subCategories: [
      "Flour & Atta",
      "Rice & Grains",
      "Pulses & Lentils",
      "Cooking Oils",
      "Spices & Masalas",
      "Sugar & Salt",
      "Dry Fruits & Nuts",
      "Pickles & Papad"
    ]
  },
  { id: '5', name_en: 'Snacks & Beverages', name_hi: 'स्नैक्स और पेय', slug: 'snacks-beverages', icon: Sandwich },
  { 
    id: '9', 
    name_en: 'Non-Veg', 
    name_hi: 'मांसाहारी', 
    slug: 'non-veg', 
    icon: Fish,
    subCategories: [
      "Eggs",
      "Packaged Meat",
      "Fresh Fish",
      "Fresh Chicken",
      "Fresh Mutton",
      "Seafood",
      "Frozen Meat"
    ]
  },
];

export const products: Product[] = [
  {
    id: 'p1',
    name_en: 'Fresh Tomato',
    name_hi: 'ताजा टमाटर',
    brand: 'Local Farms',
    category_id: '1',
    mrp: 40,
    price: 37,
    stock_qty: 100,
    image: 'https://images.unsplash.com/photo-1588694853742-705b87095935?q=80&w=400',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['vegetable', 'fresh'],
  },
  {
    id: 'p2',
    name_en: 'Organic Spinach',
    name_hi: 'जैविक पालक',
    brand: 'GreenLeaf',
    category_id: '1',
    mrp: 60,
    price: 55,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'bunch',
    pack_size: '250g',
    tags: ['vegetable', 'organic'],
  },
  {
    id: 'p3',
    name_en: 'Shimla Apple',
    name_hi: 'शिमला सेब',
    brand: 'Himalayan Orchards',
    category_id: '1',
    mrp: 150,
    price: 138,
    stock_qty: 80,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['fruit', 'fresh'],
  },
  {
    id: 'p4',
    name_en: 'Amul Gold Milk',
    name_hi: 'अमूल गोल्ड दूध',
    brand: 'Amul',
    category_id: '3',
    mrp: 32,
    price: 30,
    stock_qty: 2,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'packet',
    pack_size: '500ml',
    tags: ['dairy', 'milk'],
  },
  {
    id: 'p5',
    name_en: 'Tata Salt',
    name_hi: 'टाटा नमक',
    brand: 'Tata',
    category_id: '4',
    mrp: 25,
    price: 23,
    stock_qty: 200,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'staple'],
  },
  {
    id: 'p6',
    name_en: 'Aashirvaad Atta',
    name_hi: 'आशीर्वाद आटा',
    brand: 'Aashirvaad',
    category_id: '4',
    mrp: 250,
    price: 230,
    stock_qty: 150,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'kg',
    pack_size: '5 kg',
    tags: ['grocery', 'flour'],
  },
  {
    id: 'p7',
    name_en: 'Lays Classic Chips',
    name_hi: 'लेज़ क्लासिक चिप्स',
    brand: 'Lays',
    category_id: '5',
    mrp: 20,
    price: 18,
    stock_qty: 300,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'pack',
    pack_size: '52g',
    tags: ['snacks', 'chips'],
  },
  {
    id: 'p8',
    name_en: 'Fresh Chicken Curry Cut',
    name_hi: 'ताजा चिकन करी कट',
    brand: 'Freshoz',
    category_id: '9',
    mrp: 280,
    price: 258,
    stock_qty: 30,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: false,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['meat', 'chicken'],
  },
  {
    id: 'p9',
    name_en: 'India Gate Basmati Rice 1 kg',
    name_hi: 'इंडिया गेट बासमती चावल 1 kg',
    brand: 'India Gate',
    category_id: '4',
    mrp: 110,
    price: 101,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'rice'],
  },
  {
    id: 'p10',
    name_en: 'India Gate Basmati Rice 5 kg',
    name_hi: 'इंडिया गेट बासमती चावल 5 kg',
    brand: 'India Gate',
    category_id: '4',
    mrp: 520,
    price: 478,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'kg',
    pack_size: '5 kg',
    tags: ['grocery', 'rice'],
  },
  {
    id: 'p11',
    name_en: 'Aashirvaad Atta 1 kg',
    name_hi: 'आशीर्वाद आटा 1 kg',
    brand: 'Aashirvaad',
    category_id: '4',
    mrp: 55,
    price: 51,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'flour'],
  },
  {
    id: 'p12',
    name_en: 'Aashirvaad Atta 10 kg',
    name_hi: 'आशीर्वाद आटा 10 kg',
    brand: 'Aashirvaad',
    category_id: '4',
    mrp: 500,
    price: 460,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'kg',
    pack_size: '10 kg',
    tags: ['grocery', 'flour'],
  },
  {
    id: 'p13',
    name_en: 'Tata Sampann Toor Dal 1 kg',
    name_hi: 'टाटा सम्पन्न तूर दाल 1 kg',
    brand: 'Tata Sampann',
    category_id: '4',
    mrp: 175,
    price: 161,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'pulses'],
  },
  {
    id: 'p14',
    name_en: 'Fortune Sunflower Oil 1 L',
    name_hi: 'फॉर्च्यून सनफ्लॉवर तेल 1 L',
    brand: 'Fortune',
    category_id: '4',
    mrp: 200,
    price: 184,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'L',
    pack_size: '1 L',
    tags: ['grocery', 'oil'],
  },
  {
    id: 'p15',
    name_en: 'Fortune Sunflower Oil 5 L',
    name_hi: 'फॉर्च्यून सनफ्लॉवर तेल 5 L',
    brand: 'Fortune',
    category_id: '4',
    mrp: 975,
    price: 897,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'L',
    pack_size: '5 L',
    tags: ['grocery', 'oil'],
  },
  {
    id: 'p16',
    name_en: 'Amul Ghee 1 L',
    name_hi: 'अमूल घी 1 L',
    brand: 'Amul',
    category_id: '4',
    mrp: 780,
    price: 718,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'L',
    pack_size: '1 L',
    tags: ['grocery', 'ghee'],
  },
  {
    id: 'p17',
    name_en: 'MDH Turmeric Powder 100 g',
    name_hi: 'MDH हल्दी पाउडर 100 g',
    brand: 'MDH',
    category_id: '4',
    mrp: 90,
    price: 83,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'g',
    pack_size: '100 g',
    tags: ['grocery', 'spices'],
  },
  {
    id: 'p18',
    name_en: 'Happilo Almonds 200 g',
    name_hi: 'हैप्पीलो बादाम 200 g',
    brand: 'Happilo',
    category_id: '4',
    mrp: 240,
    price: 221,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'g',
    pack_size: '200 g',
    tags: ['grocery', 'dry fruits'],
  },
  {
    id: 'p19',
    name_en: 'Tata Salt 1 kg',
    name_hi: 'टाटा नमक 1 kg',
    brand: 'Tata',
    category_id: '4',
    mrp: 25,
    price: 23,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'staples'],
  },
  {
    id: 'p20',
    name_en: 'Sugar 1 kg',
    name_hi: 'चीनी 1 kg',
    brand: 'Local',
    category_id: '4',
    mrp: 45,
    price: 41,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'staples'],
  },
  {
    id: 'p21',
    name_en: 'Poha 500 g',
    name_hi: 'पोहा 500 g',
    brand: 'Local',
    category_id: '4',
    mrp: 45,
    price: 41,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'g',
    pack_size: '500 g',
    tags: ['grocery', 'staples'],
  },
  // Dairy Products
  {
    id: 'p22',
    name_en: 'Amul Taaza Milk',
    name_hi: 'अमूल ताजा दूध',
    brand: 'Amul',
    category_id: '3',
    mrp: 28,
    price: 26,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'packet',
    pack_size: '500 ml',
    tags: ['dairy', 'milk'],
  },
  {
    id: 'p23',
    name_en: 'Amul Taaza Milk',
    name_hi: 'अमूल ताजा दूध',
    brand: 'Amul',
    category_id: '3',
    mrp: 54,
    price: 50,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'packet',
    pack_size: '1 L',
    tags: ['dairy', 'milk'],
  },
  {
    id: 'p24',
    name_en: 'Mother Dairy Paneer',
    name_hi: 'मदर डेयरी पनीर',
    brand: 'Mother Dairy',
    category_id: '3',
    mrp: 90,
    price: 83,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'pack',
    pack_size: '200 g',
    tags: ['dairy', 'paneer'],
  },
  {
    id: 'p25',
    name_en: 'Amul Butter',
    name_hi: 'अमूल मक्खन',
    brand: 'Amul',
    category_id: '3',
    mrp: 55,
    price: 51,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'pack',
    pack_size: '100 g',
    tags: ['dairy', 'butter'],
  },
  {
    id: 'p26',
    name_en: 'Britannia Cheese Slices',
    name_hi: 'ब्रिटानिया चीज़ स्लाइस',
    brand: 'Britannia',
    category_id: '3',
    mrp: 130,
    price: 120,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'pack',
    pack_size: '200 g',
    tags: ['dairy', 'cheese'],
  },
  // Bakery
  {
    id: 'p27',
    name_en: 'Britannia White Bread',
    name_hi: 'ब्रिटानिया व्हाइट ब्रेड',
    brand: 'Britannia',
    category_id: '3',
    mrp: 45,
    price: 41,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'pack',
    pack_size: '400 g',
    tags: ['bakery', 'bread'],
  },
  {
    id: 'p28',
    name_en: 'Harvest Gold Brown Bread',
    name_hi: 'हार्वेस्ट गोल्ड ब्राउन ब्रेड',
    brand: 'Harvest Gold',
    category_id: '3',
    mrp: 50,
    price: 46,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'pack',
    pack_size: '450 g',
    tags: ['bakery', 'bread'],
  },
  // Snacks
  {
    id: 'p29',
    name_en: 'Parle-G Biscuits',
    name_hi: 'पारले-जी बिस्कुट',
    brand: 'Parle-G',
    category_id: '5',
    mrp: 10,
    price: 9,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'pack',
    pack_size: '70 g',
    tags: ['snacks', 'biscuits'],
  },
  {
    id: 'p30',
    name_en: 'Maggi 2-Minute Noodles',
    name_hi: 'मैगी 2-मिनट नूडल्स',
    brand: 'Maggi',
    category_id: '5',
    mrp: 14,
    price: 13,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'pack',
    pack_size: '70 g',
    tags: ['snacks', 'noodles'],
  },
  {
    id: 'p31',
    name_en: 'Maggi 2-Minute Noodles Family Pack',
    name_hi: 'मैगी 2-मिनट नूडल्स फैमिली पैक',
    brand: 'Maggi',
    category_id: '5',
    mrp: 56,
    price: 52,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'pack',
    pack_size: '4-pack',
    tags: ['snacks', 'noodles'],
  },
  // Tea/Coffee
  {
    id: 'p32',
    name_en: 'Tata Tea Premium',
    name_hi: 'टाटा टी प्रीमियम',
    brand: 'Tata',
    category_id: '5',
    mrp: 120,
    price: 110,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'pack',
    pack_size: '250 g',
    tags: ['beverages', 'tea'],
  },
  {
    id: 'p33',
    name_en: 'Nescafé Classic Coffee',
    name_hi: 'नेस्कैफे क्लासिक कॉफी',
    brand: 'Nescafé',
    category_id: '5',
    mrp: 150,
    price: 138,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'jar',
    pack_size: '50 g',
    tags: ['beverages', 'coffee'],
  },
  // Beverages
  {
    id: 'p34',
    name_en: 'Coca-Cola 250 ml',
    name_hi: 'कोका-कोला 250 मिली',
    brand: 'Coca-Cola',
    category_id: '5',
    mrp: 20,
    price: 18,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'bottle',
    pack_size: '250 ml',
    tags: ['beverages', 'carbonated'],
  },
  {
    id: 'p35',
    name_en: 'Coca-Cola 750 ml',
    name_hi: 'कोका-कोला 750 मिली',
    brand: 'Coca-Cola',
    category_id: '5',
    mrp: 40,
    price: 37,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'bottle',
    pack_size: '750 ml',
    tags: ['beverages', 'carbonated'],
  },
  {
    id: 'p36',
    name_en: 'Coca-Cola 2.25 L',
    name_hi: 'कोका-कोला 2.25 लीटर',
    brand: 'Coca-Cola',
    category_id: '5',
    mrp: 95,
    price: 87,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'bottle',
    pack_size: '2.25 L',
    tags: ['beverages', 'carbonated'],
  },
  {
    id: 'p37',
    name_en: 'Real Mango Juice 1 L',
    name_hi: 'रियल मैंगो जूस 1 लीटर',
    brand: 'Real',
    category_id: '5',
    mrp: 120,
    price: 110,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'pack',
    pack_size: '1 L',
    tags: ['beverages', 'juice'],
  },
  {
    id: 'p38',
    name_en: 'Tropicana Orange Juice 1 L',
    name_hi: 'ट्रॉपिकाना ऑरेंज जूस 1 लीटर',
    brand: 'Tropicana',
    category_id: '5',
    mrp: 130,
    price: 120,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'pack',
    pack_size: '1 L',
    tags: ['beverages', 'juice'],
  },
  {
    id: 'p39',
    name_en: 'Maaza 600 ml',
    name_hi: 'माज़ा 600 मिली',
    brand: 'Maaza',
    category_id: '5',
    mrp: 40,
    price: 37,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'bottle',
    pack_size: '600 ml',
    tags: ['beverages', 'mango drink'],
  },
  {
    id: 'p40',
    name_en: 'Red Bull Energy Drink 250 ml',
    name_hi: 'रेड बुल एनर्जी ड्रिंक 250 मिली',
    brand: 'Red Bull',
    category_id: '5',
    mrp: 125,
    price: 115,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'can',
    pack_size: '250 ml',
    tags: ['beverages', 'energy drink'],
  }
];
