import type { Category, Product } from '@/lib/types';
import { Apple, Carrot, Milk, Soup, Sandwich, Fish } from 'lucide-react';

export const categories: Category[] = [
  { id: '1', name_en: 'Vegetables', name_hi: 'सब्जियाँ', slug: 'vegetables', icon: Carrot },
  { id: '2', name_en: 'Fruits', name_hi: 'फल', slug: 'fruits', icon: Apple },
  { id: '3', name_en: 'Milk & Dairy', name_hi: 'दूध और डेयरी', slug: 'dairy', icon: Milk },
  { id: '4', name_en: 'Groceries', name_hi: 'किराना', slug: 'groceries', icon: Soup },
  { id: '5', name_en: 'Snacks', name_hi: 'स्नैक्स', slug: 'snacks', icon: Sandwich },
  { id: '6', name_en: 'Meat & Fish', name_hi: 'मांस और मछली', slug: 'meat-fish', icon: Fish },
];

export const products: Product[] = [
  {
    id: 'p1',
    name_en: 'Fresh Tomato',
    name_hi: 'ताजा टमाटर',
    brand: 'Local Farms',
    category_id: '1',
    mrp: 40,
    price: 35,
    stock_qty: 100,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['vegetable', 'fresh'],
  },
  {
    id: 'p2',
    name_en: 'Organic Spinach',
    name_hi: 'जैविक पालक',
    brand: 'GreenLeaf',
    category_id: '1',
    mrp: 60,
    price: 55,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'bunch',
    pack_size: '250g',
    tags: ['vegetable', 'organic'],
  },
  {
    id: 'p3',
    name_en: 'Shimla Apple',
    name_hi: 'शिमला सेब',
    brand: 'Himalayan Orchards',
    category_id: '2',
    mrp: 150,
    price: 138,
    stock_qty: 80,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['fruit', 'fresh'],
  },
  {
    id: 'p4',
    name_en: 'Amul Gold Milk',
    name_hi: 'अमूल गोल्ड दूध',
    brand: 'Amul',
    category_id: '3',
    mrp: 32,
    price: 30,
    stock_qty: 2,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'packet',
    pack_size: '500ml',
    tags: ['dairy', 'milk'],
  },
  {
    id: 'p5',
    name_en: 'Tata Salt',
    name_hi: 'टाटा नमक',
    brand: 'Tata',
    category_id: '4',
    mrp: 25,
    price: 23,
    stock_qty: 200,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'staple'],
  },
  {
    id: 'p6',
    name_en: 'Aashirvaad Atta',
    name_hi: 'आशीर्वाद आटा',
    brand: 'Aashirvaad',
    category_id: '4',
    mrp: 250,
    price: 230,
    stock_qty: 150,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'kg',
    pack_size: '5 kg',
    tags: ['grocery', 'flour'],
  },
  {
    id: 'p7',
    name_en: 'Lays Classic Chips',
    name_hi: 'लेज़ क्लासिक चिप्स',
    brand: 'Lays',
    category_id: '5',
    mrp: 20,
    price: 18,
    stock_qty: 300,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'pack',
    pack_size: '52g',
    tags: ['snacks', 'chips'],
  },
  {
    id: 'p8',
    name_en: 'Fresh Chicken Curry Cut',
    name_hi: 'ताजा चिकन करी कट',
    brand: 'Freshoz',
    category_id: '6',
    mrp: 280,
    price: 257,
    stock_qty: 30,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: false,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['meat', 'chicken'],
  },
];
