import type { Category, Product } from '@/lib/types';
import { Apple, Carrot, Milk, Soup, Sandwich, Fish } from 'lucide-react';

export const categories: Category[] = [
  { id: '1', name_en: 'Vegetables', name_hi: 'सब्जियाँ', slug: 'vegetables', icon: Carrot },
  { id: '2', name_en: 'Fruits', name_hi: 'फल', slug: 'fruits', icon: Apple },
  { id: '3', name_en: 'Milk & Dairy', name_hi: 'दूध और डेयरी', slug: 'dairy', icon: Milk },
  { id: '4', name_en: 'Groceries', name_hi: 'किराना', slug: 'groceries', icon: Soup },
  { id: '5', name_en: 'Snacks', name_hi: 'स्नैक्स', slug: 'snacks', icon: Sandwich },
  { id: '6', name_en: 'Meat & Fish', name_hi: 'मांस और मछली', slug: 'meat-fish', icon: Fish },
];

export const products: Product[] = [
  {
    id: 'p1',
    name_en: 'Fresh Tomato',
    name_hi: 'ताजा टमाटर',
    brand: 'Local Farms',
    category_id: '1',
    mrp: 40,
    price: 37,
    stock_qty: 100,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['vegetable', 'fresh'],
  },
  {
    id: 'p2',
    name_en: 'Organic Spinach',
    name_hi: 'जैविक पालक',
    brand: 'GreenLeaf',
    category_id: '1',
    mrp: 60,
    price: 55,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'bunch',
    pack_size: '250g',
    tags: ['vegetable', 'organic'],
  },
  {
    id: 'p3',
    name_en: 'Shimla Apple',
    name_hi: 'शिमला सेब',
    brand: 'Himalayan Orchards',
    category_id: '2',
    mrp: 150,
    price: 138,
    stock_qty: 80,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['fruit', 'fresh'],
  },
  {
    id: 'p4',
    name_en: 'Amul Gold Milk',
    name_hi: 'अमूल गोल्ड दूध',
    brand: 'Amul',
    category_id: '3',
    mrp: 32,
    price: 30,
    stock_qty: 2,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'packet',
    pack_size: '500ml',
    tags: ['dairy', 'milk'],
  },
  {
    id: 'p5',
    name_en: 'Tata Salt',
    name_hi: 'टाटा नमक',
    brand: 'Tata',
    category_id: '4',
    mrp: 25,
    price: 23,
    stock_qty: 200,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'staple'],
  },
  {
    id: 'p6',
    name_en: 'Aashirvaad Atta',
    name_hi: 'आशीर्वाद आटा',
    brand: 'Aashirvaad',
    category_id: '4',
    mrp: 250,
    price: 230,
    stock_qty: 150,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'kg',
    pack_size: '5 kg',
    tags: ['grocery', 'flour'],
  },
  {
    id: 'p7',
    name_en: 'Lays Classic Chips',
    name_hi: 'लेज़ क्लासिक चिप्स',
    brand: 'Lays',
    category_id: '5',
    mrp: 20,
    price: 18,
    stock_qty: 300,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'pack',
    pack_size: '52g',
    tags: ['snacks', 'chips'],
  },
  {
    id: 'p8',
    name_en: 'Fresh Chicken Curry Cut',
    name_hi: 'ताजा चिकन करी कट',
    brand: 'Freshoz',
    category_id: '6',
    mrp: 280,
    price: 258,
    stock_qty: 30,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: false,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['meat', 'chicken'],
  },
  {
    id: 'p9',
    name_en: 'India Gate Basmati Rice 1 kg',
    name_hi: 'इंडिया गेट बासमती चावल 1 kg',
    brand: 'India Gate',
    category_id: '4',
    mrp: 110,
    price: 101,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'rice'],
  },
  {
    id: 'p10',
    name_en: 'India Gate Basmati Rice 5 kg',
    name_hi: 'इंडिया गेट बासमती चावल 5 kg',
    brand: 'India Gate',
    category_id: '4',
    mrp: 520,
    price: 478,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'kg',
    pack_size: '5 kg',
    tags: ['grocery', 'rice'],
  },
  {
    id: 'p11',
    name_en: 'Aashirvaad Atta 1 kg',
    name_hi: 'आशीर्वाद आटा 1 kg',
    brand: 'Aashirvaad',
    category_id: '4',
    mrp: 55,
    price: 51,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'flour'],
  },
  {
    id: 'p12',
    name_en: 'Aashirvaad Atta 10 kg',
    name_hi: 'आशीर्वाद आटा 10 kg',
    brand: 'Aashirvaad',
    category_id: '4',
    mrp: 500,
    price: 460,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'kg',
    pack_size: '10 kg',
    tags: ['grocery', 'flour'],
  },
  {
    id: 'p13',
    name_en: 'Tata Sampann Toor Dal 1 kg',
    name_hi: 'टाटा सम्पन्न तूर दाल 1 kg',
    brand: 'Tata Sampann',
    category_id: '4',
    mrp: 175,
    price: 161,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'pulses'],
  },
  {
    id: 'p14',
    name_en: 'Fortune Sunflower Oil 1 L',
    name_hi: 'फॉर्च्यून सनफ्लॉवर तेल 1 L',
    brand: 'Fortune',
    category_id: '4',
    mrp: 200,
    price: 184,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'L',
    pack_size: '1 L',
    tags: ['grocery', 'oil'],
  },
  {
    id: 'p15',
    name_en: 'Fortune Sunflower Oil 5 L',
    name_hi: 'फॉर्च्यून सनफ्लॉवर तेल 5 L',
    brand: 'Fortune',
    category_id: '4',
    mrp: 975,
    price: 897,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'L',
    pack_size: '5 L',
    tags: ['grocery', 'oil'],
  },
  {
    id: 'p16',
    name_en: 'Amul Ghee 1 L',
    name_hi: 'अमूल घी 1 L',
    brand: 'Amul',
    category_id: '4',
    mrp: 780,
    price: 718,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'L',
    pack_size: '1 L',
    tags: ['grocery', 'ghee'],
  },
  {
    id: 'p17',
    name_en: 'MDH Turmeric Powder 100 g',
    name_hi: 'MDH हल्दी पाउडर 100 g',
    brand: 'MDH',
    category_id: '4',
    mrp: 90,
    price: 83,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'g',
    pack_size: '100 g',
    tags: ['grocery', 'spices'],
  },
  {
    id: 'p18',
    name_en: 'Happilo Almonds 200 g',
    name_hi: 'हैप्पीलो बादाम 200 g',
    brand: 'Happilo',
    category_id: '4',
    mrp: 240,
    price: 221,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'g',
    pack_size: '200 g',
    tags: ['grocery', 'dry fruits'],
  },
  {
    id: 'p19',
    name_en: 'Tata Salt 1 kg',
    name_hi: 'टाटा नमक 1 kg',
    brand: 'Tata',
    category_id: '4',
    mrp: 25,
    price: 23,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'staples'],
  },
  {
    id: 'p20',
    name_en: 'Sugar 1 kg',
    name_hi: 'चीनी 1 kg',
    brand: 'Local',
    category_id: '4',
    mrp: 45,
    price: 41,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'quick',
    is_veg: true,
    unit: 'kg',
    pack_size: '1 kg',
    tags: ['grocery', 'staples'],
  },
  {
    id: 'p21',
    name_en: 'Poha 500 g',
    name_hi: 'पोहा 500 g',
    brand: 'Local',
    category_id: '4',
    mrp: 45,
    price: 41,
    stock_qty: 50,
    image: 'https://placehold.co/400x400.png',
    delivery_mode: 'ecom',
    is_veg: true,
    unit: 'g',
    pack_size: '500 g',
    tags: ['grocery', 'staples'],
  }
];
